server:
  port: ${SERVER_PORT:8081}

web:
  allowedOrigins: ${ALLOWED_ORIGINS:http://localhost}

security:
  token:
    issuer: ${TOKEN_ISSUER:LockBox}
    secret: ${TOKEN_SECRET:secret}
    duration: ${TOKEN_DURATION:15m}

spring:
  application:
    name: odontaval
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:2345/odontaval_db}
    username: ${DB_USER:developer}
    password: ${DB_PASSWORD:12345678}
    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: none
      show-sql: false
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration